#movie-new
#Author:(Alireza Ghaderi)

version: "3.9"

services:
  db:
    image: postgres:15
    container_name: movie_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: movie_api
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: >
      sh -c "poetry run alembic upgrade head &&
             poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000"

volumes:
  postgres_data:
